#!/usr/bin/env python3
"""Regenerate the private symbol map after replacing the vendored SQLite files."""

import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SQLITE = ROOT / "packages/react-native-nitro-sqlite/cpp/sqlite"
HEADER = SQLITE / "sqlite3.h"
OUTPUT = SQLITE / "sqlite3-symbol-prefix.h"
METADATA_SYMBOLS = {
    "sqlite3_column_database_name",
    "sqlite3_column_database_name16",
    "sqlite3_column_origin_name",
    "sqlite3_column_origin_name16",
    "sqlite3_column_table_name",
    "sqlite3_column_table_name16",
}
CONDITIONAL_SYMBOLS = {
    "#ifdef SQLITE_ENABLE_COLUMN_METADATA": METADATA_SYMBOLS,
    "#if !defined(SQLITE_THREADSAFE) || SQLITE_THREADSAFE != 0": {
        "sqlite3_mutex_alloc", "sqlite3_mutex_enter", "sqlite3_mutex_free",
        "sqlite3_mutex_held", "sqlite3_mutex_leave", "sqlite3_mutex_notheld",
        "sqlite3_mutex_try",
    },
    "#ifndef SQLITE_OMIT_PROGRESS_CALLBACK": {"sqlite3_progress_handler"},
    "#ifndef SQLITE_OMIT_SHARED_CACHE": {"sqlite3_enable_shared_cache"},
    "#if !defined(SQLITE_OMIT_TRACE) && !defined(SQLITE_OMIT_DEPRECATED)": {
        "sqlite3_profile", "sqlite3_trace",
    },
}


def main() -> None:
    source = HEADER.read_text()
    source = re.sub(r"/\*.*?\*/", "", source, flags=re.DOTALL)
    declarations = re.findall(r"\bSQLITE_API\b[^;]*;", source, flags=re.DOTALL)
    symbols = set()
    for declaration in declarations:
        match = re.search(r"\b(sqlite3_[A-Za-z0-9_]+)\s*(?=\(|\[|;)", declaration)
        if match:
            symbols.add(match.group(1))

    if "sqlite3_version" not in symbols or "sqlite3_open" not in symbols:
        raise RuntimeError("Could not find the SQLite API and exported data symbols")

    lines = [
        "/* Generated by scripts/generate-sqlite-symbol-prefix.py from sqlite3.h. */",
        "#ifndef NITRO_SQLITE3_SYMBOL_PREFIX_H",
        "#define NITRO_SQLITE3_SYMBOL_PREFIX_H",
        "",
    ]
    guarded = set().union(*CONDITIONAL_SYMBOLS.values())
    lines.extend(f"#define {symbol} nitro_{symbol}" for symbol in sorted(symbols - guarded))
    for condition, members in CONDITIONAL_SYMBOLS.items():
        lines.extend(["", condition])
        lines.extend(f"#define {symbol} nitro_{symbol}" for symbol in sorted(symbols & members))
        lines.append("#endif")
    lines.extend([
        "",
        "/* The optional statically linked extension belongs to this SQLite instance. */",
        "#define sqlite3_vec_init nitro_sqlite3_vec_init",
        "#define sqlite3_vec_numpy_init nitro_sqlite3_vec_numpy_init",
        "#define sqlite3_vec_static_blobs_init nitro_sqlite3_vec_static_blobs_init",
        "",
        "#endif",
        "",
    ])
    generated = "\n".join(lines)
    if "--check" in sys.argv:
        if OUTPUT.read_text() != generated:
            raise RuntimeError("SQLite symbol map is stale; regenerate it after updating sqlite3.h")
        return
    OUTPUT.write_text(generated)


if __name__ == "__main__":
    main()
