name: Lint C++

on:
  push:
    branches:
      - main
    paths: &cpp_paths
      - ".github/workflows/lint-cpp.yml"
      - ".clang-format"
      - "scripts/clang-format.sh"
      - "packages/react-native-nitro-sqlite/cpp/**"
      - "packages/react-native-nitro-sqlite/tests/cpp/**"
  pull_request:
    paths: *cpp_paths

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Format C++
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: oven-sh/setup-bun@v2

      - name: Run clang-format
        run: bun run lint-cpp

      - name: Verify no files have changed after format
        run: git diff --exit-code HEAD -- . ':(exclude)bun.lock'
